# SPDX-License-Identifier: GPL-2.0
# v4l2loopback for the OV32C4: a fixed node number, a name that looks
# like a camera, and exclusive_caps=1 so the node reports itself as
# capture only (Chromium drops a device that also reports VIDEO_OUTPUT).
# The format is pinned by set-caps from the udev rule, so the capture
# side is valid even with no feeder running.
options v4l2loopback devices=1 video_nr=42 card_label="Lenovo OV32C4" exclusive_caps=1
